Feature/exercicio 01
hernangior/orion-bootcamp pull request #1
Opened 2023-10-12 14:23 UTC by hernangior

Solicitação de pull request.

Envio de atividade do exercício 01.

2023-10-12 14:26 UTC, hernangior commented
Aguardando solicitação de pull request referente ao envio de atividade do exercício 01.

2023-10-12 15:23 UTC, hernangior commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ squad-bellatrix ][ hernandez giordano ] Exercício 01](https://trello.com/c/FCWv3jyM/104-squad-bellatrix-hernandez-giordano-exerc%C3%ADcio-01)

2023-10-13 19:16 UTC, matheus-yudi-newrizon requested changes

2023-10-13 19:16 UTC, matheus-yudi-newrizon commented on src/index.ts
> +function showNumberOfWowels() {
typo *Vowels

Faltou a documentação e o tipo de retorno do método.

2023-10-13 19:16 UTC, matheus-yudi-newrizon commented on src/index.ts
> +// função que retorna a quantidade de vogais da palavra passada.
Dica: poderia usar o modelo de documentação do TSDoc (https://tsdoc.org/)

2023-10-13 19:45 UTC, hernangior commented
Mudanças efetuadas

2023-10-13 20:11 UTC, matheus-yudi-newrizon requested changes

2023-10-13 20:11 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    const vowelsFound     = word.match(regexExpression);
Não seria uma boa considerar as letras em uppercase também? Nesse caso, para não precisar mapear todas as vogais e suas variantes (maiúscula/minúscula), você poderia transformar a palavra toda para lowercase ou uppercase.

2023-10-13 20:11 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    (divOutput)? divOutput.innerHTML = `# A quantidade de vogais é: ${numberOfVowels.toString()}`:'erro ao calcular';
É bom deixar o nosso código o mais legível sempre que possível. Para isso, é uma boa adicionar espaços entre as declarações, agrupar as variáveis/execuçõe e identar o código.

2023-10-13 20:11 UTC, matheus-yudi-newrizon commented on src/index.ts
> +console.log(getNumberOfVowels("Hernandez"));
Poderia colocar uma mensagem mais clara no momento do console para que seja possível visualizar no inspetor, ou então alterar para um alert()

2023-10-13 20:11 UTC, matheus-yudi-newrizon commented on src/index.ts
> +function showNumberOfVowels() : void {
Ficou um espaço entre "() : void" -> "(): void"

2023-10-13 20:11 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    const inputWord      = document.getElementById('inputPalavra') as HTMLInputElement;
É uma boa prática não mesclar idiomas na declaração de variáveis, métodos e tipos. Seguindo o padrão do código, o ID dos elementos poderia também estar em inglês.

2023-10-13 20:31 UTC, hernangior commented on src/index.ts
> +    const inputWord      = document.getElementById('inputPalavra') as HTMLInputElement;
Correção aplicada

```typescript
  // b) Exemplo de uso com uma palavra recebida via input no formulário.
  function showNumberOfVowels(): void {
    const inputWord = document.getElementById("input-task-1") as HTMLInputElement;
```

2023-10-13 20:32 UTC, hernangior commented on src/index.ts
> +function showNumberOfVowels() : void {
Correção aplicada:

```typescript
  // b) Exemplo de uso com uma palavra recebida via input no formulário.
  function showNumberOfVowels(): void {
    const inputWord = document.getElementById("input-task-1") as HTMLInputElement;
```

2023-10-13 20:33 UTC, hernangior commented on src/index.ts
> +console.log(getNumberOfVowels("Hernandez"));
Correção aplicada:

```typescript
  // a) Exemplo de uso com uma palavra recebida via parâmetro da função.
  console.log("# função para contagem de vogais de uma palavra dada");
  console.log('# teste executado par a palavra: "Hernandez"');
  console.log(
    `A quantidade de vogais da palavra informada é: [${getNumberOfVowels(
      "Hernandez"
    )}]`
  );
```

2023-10-13 20:33 UTC, hernangior commented on src/index.ts
> +    (divOutput)? divOutput.innerHTML = `# A quantidade de vogais é: ${numberOfVowels.toString()}`:'erro ao calcular';
Correção aplicada:

```typescript
  // b) Exemplo de uso com uma palavra recebida via input no formulário.
  function showNumberOfVowels(): void {
    const inputWord = document.getElementById("input-task-1") as HTMLInputElement;
    const numberOfVowels = getNumberOfVowels(inputWord.value);
    let divOutput = document.getElementById("div-output");
    if (divOutput) {
      divOutput.innerHTML = `# A quantidade de vogais é: ${numberOfVowels.toString()}`;
    }
  }
```

2023-10-13 20:34 UTC, hernangior commented on src/index.ts
> +    const vowelsFound     = word.match(regexExpression);
Correção aplicada:

```typescript
function getNumberOfVowels(word: string): number {
    const regexExpression = /[aeiouàáâãäåæçèéêëìíîïðòóôõöùúûüýÿ]/gi;
    const vowelsFound = word.toLowerCase().match(regexExpression);
    return vowelsFound ? vowelsFound.length : 0;
  }
```

2023-10-13 21:13 UTC, matheus-yudi-newrizon commented on src/index.ts
> +  console.log('# teste executado par a palavra: "Hernandez"');
*para a palavra

2023-10-13 21:13 UTC, matheus-yudi-newrizon approved these changes

2023-10-13 22:02 UTC, merged