Feature/exercicio 02
hernangior/orion-bootcamp pull request #2
Opened 2023-10-12 18:35 UTC by hernangior

**PULL REQUEST REGISTRADO**

Solicitação de pull request.

Envio de atividades do exercício 02.

2023-10-12 18:36 UTC, hernangior commented
Aguardando solicitação de pull request referente ao envio de atividade do exercício 02.

2023-10-12 18:37 UTC, hernangior commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ squad-bellatrix ][ hernandez giordano ] Exercício 02](https://trello.com/c/xro1KVTw/105-squad-bellatrix-hernandez-giordano-exerc%C3%ADcio-02)

2023-10-13 21:10 UTC, matheus-yudi-newrizon requested changes
Não dupliquei os apontamentos para não poulir o PR, mas alguns dos comentários se aplicam para a maioria dos métodos implementados.

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on .github/workflows/feature-exercicio-02.yml
Aqui daria para deixar a branch de disparo do actions como "feature/**", englobando qualquer branch com esse prefixo.

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on README.md
Como as features do exercício 1 ainda não subiram para a develop, talvez seja bom alterar o destino desse PR para lá. Aí nesse ficam só as coisas novas.

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    let lista : Array <Object> = [{
Como estamos trabalhando com o TS, temos a possibilidade de criar interfaces/enums (https://typescriptlang.org/docs/handbook/interfaces.html) para tipar os nossos recursos.

Seria legal gerar uma interface para as pessoas da lista e tipar não só a lista, mas os parâmetros, resultados e variáveis.

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    //console.log("# Lista de dados em array para Exercício 02:");
Observar os apontamentos do PR do exercício anterior, sobre código comentado, identação, etc.

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    function functionalGetBioById(id: number): string {
Seria legal o método não fazer uso de uma variável externa (newList). Para que o método seja considerado "puro" e não sofra efeitos colaterais, seria legal receber a lista também via parâmetro.

**OBS: Serve também para os demais métodos.**

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    function imperativeGetBioById(id: number): string{
Observar os apontamentos do PR do exercício anterior, sobre documentação dos métodos.

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on src/index.ts
> +                {
A interface que eu mencionei, poderia ser útil nesse cast.

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on src/index.ts
> +            if (item.id === id) {
Para não precisar de 2 variáveis, poderia realizar esse if direto com o próprio `lista[i]`

2023-10-13 21:10 UTC, matheus-yudi-newrizon commented on src/index.ts
> +    function functionalUpdateItemById(id: number, newContent: string, type: string): void {
Poderia tipar o type como `type: "bio" | "name"`

2023-10-14 02:37 UTC, merged

2023-10-14 02:58 UTC, hernangior commented on .github/workflows/feature-exercicio-02.yml
Correção aplicada:

```bash
# This is a basic workflow to help you get started with Actions

name: CI-EXERCISES

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ " feature/**" ]
```

2023-10-14 03:07 UTC, hernangior commented on src/index.ts
> +    //console.log("# Lista de dados em array para Exercício 02:");
**Correção aplicada:**

Código devidamente comentado e identado.

2023-10-14 03:14 UTC, hernangior commented on src/index.ts
> +    function functionalUpdateItemById(id: number, newContent: string, type: string): void {
Correção aplicada:

```typescript
  function functionalUpdateItemById(
    id: number,
    newContent: string,
    type: "bio" | "name"
  ): string {
...
```

2023-10-14 03:18 UTC, hernangior commented on README.md
Correção aplicada:

✔ **feature/exercicio-01** mergeada com **develop** via **pull request**

✔ **feature/exercicio-03** mergeada com **develop** via **pull request**

✔ **feature/exercicio-02** atualizada com dados de **develop**

2023-10-14 03:36 UTC, hernangior commented on src/index.ts
> +            if (item.id === id) {
Correção aplicada:

Na tentativa de fazer a chamada usando o próprio "lista[i]" o erro retornado é :

`Property 'id' does not exist on type 'Object'.ts(2339)`

Mas a correção é aplicada na função que demonstra de forma funcional a mesma necessidade:

```typescript
  function functionalGetBioById(id: number): string {
    let person = newList.find((item) => item.id === id);
    return person ? person.bio : "";
  }
```

2023-10-14 03:41 UTC, hernangior commented on src/index.ts
> +    let lista : Array <Object> = [{
**Correção aplicada:**

A lista foi carregada da mesma forma que no exercício para demonstrar seu uso por meio da interface chamada "Person":

```typescript
  class Person {
    id: number;
    name: string;
    bio: string;
    constructor(id: number, name: string, bio: string) {
      this.id = id;
      this.name = name;
      this.bio = bio;
    }
  }
```

para acessar as informações foi desenvolvido o método para converter o array em uma lista tipada do tipo "Person":

```typescript
  function convertArrayToList(array: Array<any>): Array<Person> {
    return array.map((obj) => new Person(obj.id, obj.name, obj.bio));
  }
```

a nova lista foi tipada e carregada por meio da chamada do método:

`let newList = convertArrayToList(lista);`

2023-10-14 03:43 UTC, hernangior commented on src/index.ts
> +                {
**Correção aplicada**

A seção da função se destinava a mencionar como o método poderia ser executada de forma mais procedural, mas a chamada é feita da forma necessária usando-se a interface na maneira funcional em :

```typescript
  function functionalGetBioById(id: number): string {
    let person = newList.find((item) => item.id === id);
    return person ? person.bio : "";
  }
```

2023-10-14 03:44 UTC, hernangior commented on src/index.ts
> +    function imperativeGetBioById(id: number): string{
**Correção aplicada**

Métodos devidamente documentados

2023-10-14 04:05 UTC, hernangior commented on src/index.ts
> +    function functionalGetBioById(id: number): string {
**Correção Aplicada:**

A chamada da variável é feita via parâmetro:

```typescript
  function functionalGetBioById(id: number, list : Person[]): string {
    let person = list.find((item) => item.id === id);
    return person ? person.bio : "";
  }
```

```typescript
  function functionalGetNameById(id: number, list: Person[]): string {
    let person = list.find((item) => item.id === id);
    return person ? person.name : "";
  }
```

```typescript
  function functionalDeleteItemById(id: number, list: Person[]): string {
    let index = list.findIndex((item) => item.id === id);
    let result;
    if (index !== -1) {
      list.splice(index, 1);
      result = "success";
    } else {
      result = "nada a excluir";
    }
    return result;
  }
```
```typescript
  function refreshArray(list : Person[]): void {
    let listString = JSON.stringify(list, null, 2);
    listString = `
      <label>Dados do array:</label>
      <pre>
          <code>
          ${listString}
          </code>
      </pre>
      <hr>
      <label><b>De acordo com as alterações realizadas abaixo esse objeto será dinâmicamente atualizado</b></label>
      `;
    let divTask2Array = document.getElementById("div-task-2-array");
    if (divTask2Array) {
      divTask2Array.innerHTML = listString;
    }
  }
```