Feature/exercicio 03
hernangior/orion-bootcamp pull request #3
Opened 2023-10-13 18:17 UTC by hernangior

Solicitação de pull request.

Envio de atividade do exercício 03.

2023-10-13 18:18 UTC, hernangior commented
Aguardando solicitação de pull request referente ao envio de atividade do exercício 01.

2023-10-13 18:20 UTC, hernangior commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ squad-bellatrix ][ hernandez giordano ] Exercício 03](https://trello.com/c/sdsZp9tp/106-squad-bellatrix-hernandez-giordano-exerc%C3%ADcio-03)

2023-10-13 22:43 UTC, dairsposito requested changes

2023-10-13 22:43 UTC, dairsposito commented on src/index.ts
> +      ? (output = `O item com ID informado como [${input}] foi removido da lista`)
Não está atualizando o JSON da lista exibido em tela ao remover o item.

2023-10-13 22:43 UTC, dairsposito commented on src/index.ts
> +      : (output = `A Bio referente ao ID informado como [${inputId}] foi alterada!`);
Não está atualizando a lista em JSON no topo da página.

2023-10-13 22:43 UTC, dairsposito commented on src/index.ts
Documentar todas as funções.

2023-10-13 22:43 UTC, dairsposito commented on src/index.ts
> +    let regexExpression = /[aeiouàáâãäåæçèéêëìíîïðòóôõöùúûüýÿ]/gi;
Considerar apenas as vogais em português.

2023-10-14 00:57 UTC, hernangior commented on src/index.ts
> +    let regexExpression = /[aeiouàáâãäåæçèéêëìíîïðòóôõöùúûüýÿ]/gi;
Correção efetuada:

```typescript
function getNumberOfVowels(word: string): number {
    let regexExpression = /[aeiouàáâãçèéêìíòóôõùú]/gi;
```

2023-10-14 01:43 UTC, hernangior commented on src/index.ts
Funções documentadas

2023-10-14 02:11 UTC, hernangior commented on src/index.ts
> +      : (output = `A Bio referente ao ID informado como [${inputId}] foi alterada!`);
Correção aplicada:

```typescript
  /**
   *
   * Função que atualiza os valores do array de elementos no respectivo elemento HTML
   *
   * @param   - sem parâmetros
   * @returns void - sem retorno, setado diretamente no componente HTML
   *
   * @beta
   */
  function refreshArray(): void {
    let listString = JSON.stringify(newList, null, 2);
    listString = `
      <label>Dados do array:</label>
      <pre>
          <code>
          ${listString}
          </code>
      </pre>
      <hr>
      <label><b>De acordo com as alterações realizadas abaixo esse objeto será dinâmicamente atualizado</b></label>
      `;
    let divTask2Array = document.getElementById("div-task-2-array");
    if (divTask2Array) {
      divTask2Array.innerHTML = listString;
    }
  }
```

2023-10-14 02:11 UTC, hernangior commented on src/index.ts
> +      ? (output = `O item com ID informado como [${input}] foi removido da lista`)
Correção aplicada:

```typescript
  /**
   *
   * Função que atualiza os valores do array de elementos no respectivo elemento HTML
   *
   * @param   - sem parâmetros
   * @returns void - sem retorno, setado diretamente no componente HTML
   *
   * @beta
   */
  function refreshArray(): void {
    let listString = JSON.stringify(newList, null, 2);
    listString = `
      <label>Dados do array:</label>
      <pre>
          <code>
          ${listString}
          </code>
      </pre>
      <hr>
      <label><b>De acordo com as alterações realizadas abaixo esse objeto será dinâmicamente atualizado</b></label>
      `;
    let divTask2Array = document.getElementById("div-task-2-array");
    if (divTask2Array) {
      divTask2Array.innerHTML = listString;
    }
  }
```

2023-10-14 02:31 UTC, dairsposito approved these changes

2023-10-14 02:37 UTC, merged